"""
Generated by qenerate plugin=pydantic_v1. DO NOT MODIFY MANUALLY!
"""
from collections.abc import Callable  # noqa: F401 # pylint: disable=W0611
from datetime import datetime  # noqa: F401 # pylint: disable=W0611
from enum import Enum  # noqa: F401 # pylint: disable=W0611
from typing import (  # noqa: F401 # pylint: disable=W0611
    Any,
    Optional,
    Union,
)

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    Extra,
    Field,
    Json,
)


DEFINITION = """
query GcrRepos {
  apps: apps_v1 {
    gcrRepos {
      project {
        name
      }
      items {
        name
        mirror {
          url
          pullCredentials {
            path
            field
            version
            format
          }
          tags
          tagsExclude
        }
        artifactRegistry {
          enabled
          location
        }
      }
    }
  }
}
"""


class ConfiguredBaseModel(BaseModel):
    class Config:
        smart_union=True
        extra=Extra.forbid


class GcpProjectV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")


class VaultSecretV1(ConfiguredBaseModel):
    path: str = Field(..., alias="path")
    field: str = Field(..., alias="field")
    version: Optional[int] = Field(..., alias="version")
    q_format: Optional[str] = Field(..., alias="format")


class ContainerImageMirrorV1(ConfiguredBaseModel):
    url: str = Field(..., alias="url")
    pull_credentials: Optional[VaultSecretV1] = Field(..., alias="pullCredentials")
    tags: Optional[list[str]] = Field(..., alias="tags")
    tags_exclude: Optional[list[str]] = Field(..., alias="tagsExclude")


class AppArtifactRegistryConfV1(ConfiguredBaseModel):
    enabled: bool = Field(..., alias="enabled")
    location: str = Field(..., alias="location")


class AppGcrReposItemsV1(ConfiguredBaseModel):
    name: str = Field(..., alias="name")
    mirror: Optional[ContainerImageMirrorV1] = Field(..., alias="mirror")
    artifact_registry: Optional[AppArtifactRegistryConfV1] = Field(..., alias="artifactRegistry")


class AppGcrReposV1(ConfiguredBaseModel):
    project: GcpProjectV1 = Field(..., alias="project")
    items: list[AppGcrReposItemsV1] = Field(..., alias="items")


class AppV1(ConfiguredBaseModel):
    gcr_repos: Optional[list[AppGcrReposV1]] = Field(..., alias="gcrRepos")


class GcrReposQueryData(ConfiguredBaseModel):
    apps: Optional[list[AppV1]] = Field(..., alias="apps")


def query(query_func: Callable, **kwargs: Any) -> GcrReposQueryData:
    """
    This is a convenience function which queries and parses the data into
    concrete types. It should be compatible with most GQL clients.
    You do not have to use it to consume the generated data classes.
    Alternatively, you can also mime and alternate the behavior
    of this function in the caller.

    Parameters:
        query_func (Callable): Function which queries your GQL Server
        kwargs: optional arguments that will be passed to the query function

    Returns:
        GcrReposQueryData: queried data parsed into generated classes
    """
    raw_data: dict[Any, Any] = query_func(DEFINITION, **kwargs)
    return GcrReposQueryData(**raw_data)
