# qenerate: plugin=pydantic_v1

query GcrRepos {
  apps: apps_v1 {
    gcrRepos {
      project {
        name
      }
      items {
        name
        mirror {
          url
          pullCredentials {
            ...VaultSecret
          }
          tags
          tagsExclude
        }
        artifactRegistry {
          enabled
          location
        }
      }
    }
  }
}
